## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [85]:
import tensorflow as tf

In [86]:
tf.__version__

'1.14.0'

In [87]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default
tf.enable_eager_execution()

#Check eager execution is enabled or not
tf.executing_eagerly()

True

### Collect Data

In [88]:
# Im running in my local pc
#from google.colab import drive
#drive.mount('/gdrive')

In [89]:
import pandas as pd

In [90]:
data = pd.read_csv('prices.csv')

### Check all columns in the dataset

In [91]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB

### Drop columns `date` and  `symbol`

In [92]:
data.drop(['date', 'symbol'], axis=1, inplace=True)

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 5 columns):
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5)
memory usage: 32.5 MB

In [94]:
data.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [95]:
data.shape

(851264, 5)

In [96]:
data = data[0:1000]
data.shape

(1000, 5)

In [97]:
data['volume'] = data['volume']/1000000

In [98]:
data.head()

         open       close         low        high  volume
0  123.430000  125.839996  122.309998  126.250000  2.1636
1  125.239998  119.980003  119.940002  125.540001  2.3864
2  116.379997  114.949997  114.930000  119.739998  2.4895
3  115.480003  116.620003  113.500000  117.440002  2.0063
4  117.010002  114.970001  114.089996  117.330002  1.4086

### Divide the data into train and test sets

In [99]:
from sklearn.model_selection import train_test_split

In [100]:
X =  data.drop("volume", axis=1)
Y =  data.pop("volume")

In [101]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=7)

#### Convert Training and Test Data to numpy float32 arrays

In [102]:
import numpy as np

In [103]:
xtr = np.asarray(X_train, dtype='float32')
xte = np.asarray(X_test, dtype='float32')
ytr = np.asarray(y_train, dtype='float32')
yte = np.asarray(y_test, dtype='float32')

In [104]:
xtr.shape, X_train.shape

((670, 4), (670, 4))

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [105]:
from sklearn.preprocessing import Normalizer

In [106]:
xtr = Normalizer().fit_transform(xtr)
xte = Normalizer().fit_transform(xte)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [124]:
W = tf.Variable(tf.random_normal(shape=[4, 1]), name="Weights")
b = tf.Variable(tf.random_normal(shape=[1]), name="Bias")

2.Define a function to calculate prediction

In [125]:
def pred(x, w, b):
  return tf.add(tf.matmul(x, W),b,name='output')

In [126]:
y_pred = pred(xtr, W, b)

3.Loss (Cost) Function [Mean square error]

In [127]:
def loss_calc(y, y_):
  return tf.reduce_mean(tf.square(y-y_),name='Loss')

In [128]:
loss = loss_calc(ytr, y_pred)
print(loss)

tf.Tensor(331.9501, shape=(), dtype=float32)

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [136]:
def fn_train(x,y,W,b,learn_rate):
  with tf.GradientTape() as t :
     t.watch([W,b])
     y_pred = pred(x,W,b)
     loss = loss_calc(y,y_pred)
  
  dc_dw, dc_db = t.gradient(loss, [W, b])
  W = W - learn_rate * dc_dw
  b = b - learn_rate * dc_db
  return W,b

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [195]:
for i in range (100):
  W,b = fn_train(xtr, ytr, W,b, 0.01)
  y_pred = pred(xtr, W, b)
  train_loss = loss_calc(ytr, y_pred)
  if i % 5 == 0:
    print('Training loss at step: ', i, ' is ', train_loss)

Training loss at step:  0  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  5  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  10  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  15  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  20  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  25  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  30  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  35  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  40  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  45  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  50  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  55  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  60  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  65  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  70  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  75  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  80  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  85  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  90  is  tf.Tensor(285.47394, shape=(), dtype=float32)
Training loss at step:  95  is  tf.Tensor(285.47394, shape=(), dtype=float32)

### Get the shapes and values of W and b

In [141]:
W

<tf.Tensor: id=10264, shape=(4, 1), dtype=float32, numpy=
array([[1.2170423],
       [1.5658139],
       [0.8839249],
       [2.3107197]], dtype=float32)>

In [143]:
W.shape

TensorShape([Dimension(4), Dimension(1)])

In [148]:
b

In [147]:
b.shape

TensorShape([Dimension(1)])

### Model Prediction on 1st Examples in Test Dataset

In [151]:
y_pred = pred(xte, W, b)
test_loss = loss_calc(yte, y_pred)

In [152]:
test_loss

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [177]:
df = pd.read_csv('Iris.csv')

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

### Splitting the data into feature set and target set

In [178]:
X =  df.drop(["Id", "Species"], axis=1)
y =  df.pop("Species")

In [179]:
y = pd.get_dummies( y, columns = ['Species'] )

In [180]:
X.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [181]:
y.head()

   Iris-setosa  Iris-versicolor  Iris-virginica
0            1                0               0
1            1                0               0
2            1                0               0
3            1                0               0
4            1                0               0

In [223]:
from sklearn.model_selection import train_test_split

In [233]:
train_x, test_x, train_y, test_y = train_test_split(X, y, test_size=0.30)

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [234]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  #tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

In [203]:
features = np.asarray(X)
labels = np.asarray(y)

In [184]:
features.shape

(150, 4)

In [235]:
model.compile(tf.keras.optimizers.SGD(), loss='categorical_crossentropy', metrics=['accuracy'])

### Model Training

In [236]:
model.fit(train_x, train_y, epochs=100)

Epoch 1/100
105/105 [==============================] - 0s 554us/sample - loss: 1.8698 - acc: 0.1524
Epoch 2/100
105/105 [==============================] - 0s 41us/sample - loss: 1.2912 - acc: 0.4571
Epoch 3/100
105/105 [==============================] - 0s 37us/sample - loss: 1.2002 - acc: 0.5810
Epoch 4/100
105/105 [==============================] - 0s 31us/sample - loss: 1.1607 - acc: 0.4095
Epoch 5/100
105/105 [==============================] - 0s 33us/sample - loss: 1.0999 - acc: 0.6095
Epoch 6/100
105/105 [==============================] - 0s 35us/sample - loss: 1.0731 - acc: 0.4476
Epoch 7/100
105/105 [==============================] - 0s 46us/sample - loss: 1.0417 - acc: 0.6190
Epoch 8/100
105/105 [==============================] - 0s 34us/sample - loss: 0.9951 - acc: 0.4571
Epoch 9/100
105/105 [==============================] - 0s 29us/sample - loss: 0.9660 - acc: 0.5143
Epoch 10/100
105/105 [==============================] - 0s 31us/sample - loss: 0.9945 - acc: 0.5048
Epoch 11/100
105/105 [==============================] - 0s 47us/sample - loss: 0.9048 - acc: 0.4286
Epoch 12/100
105/105 [==============================] - 0s 38us/sample - loss: 0.8944 - acc: 0.5810
Epoch 13/100
105/105 [==============================] - 0s 32us/sample - loss: 0.8500 - acc: 0.5143
Epoch 14/100
105/105 [==============================] - 0s 32us/sample - loss: 0.8273 - acc: 0.5810
Epoch 15/100
105/105 [==============================] - 0s 35us/sample - loss: 0.8112 - acc: 0.6381
Epoch 16/100
105/105 [==============================] - 0s 30us/sample - loss: 0.7946 - acc: 0.5143
Epoch 17/100
105/105 [==============================] - 0s 39us/sample - loss: 0.7686 - acc: 0.6571
Epoch 18/100
105/105 [==============================] - 0s 35us/sample - loss: 0.7526 - acc: 0.6857
Epoch 19/100
105/105 [==============================] - 0s 30us/sample - loss: 0.7435 - acc: 0.5619
Epoch 20/100
105/105 [==============================] - 0s 29us/sample - loss: 0.7366 - acc: 0.7048
Epoch 21/100
105/105 [==============================] - 0s 41us/sample - loss: 0.7083 - acc: 0.6762
Epoch 22/100
105/105 [==============================] - 0s 34us/sample - loss: 0.6879 - acc: 0.8095
Epoch 23/100
105/105 [==============================] - 0s 29us/sample - loss: 0.7034 - acc: 0.7238
Epoch 24/100
105/105 [==============================] - 0s 42us/sample - loss: 0.7054 - acc: 0.6667
Epoch 25/100
105/105 [==============================] - 0s 33us/sample - loss: 0.6503 - acc: 0.8000
Epoch 26/100
105/105 [==============================] - 0s 31us/sample - loss: 0.6496 - acc: 0.7619
Epoch 27/100
105/105 [==============================] - 0s 29us/sample - loss: 0.6418 - acc: 0.7714
Epoch 28/100
105/105 [==============================] - 0s 44us/sample - loss: 0.6281 - acc: 0.7714
Epoch 29/100
105/105 [==============================] - 0s 33us/sample - loss: 0.6350 - acc: 0.7810
Epoch 30/100
105/105 [==============================] - 0s 31us/sample - loss: 0.6023 - acc: 0.8857
Epoch 31/100
105/105 [==============================] - 0s 40us/sample - loss: 0.6075 - acc: 0.7429
Epoch 32/100
105/105 [==============================] - 0s 35us/sample - loss: 0.6015 - acc: 0.8381
Epoch 33/100
105/105 [==============================] - 0s 30us/sample - loss: 0.5798 - acc: 0.8476
Epoch 34/100
105/105 [==============================] - 0s 35us/sample - loss: 0.5843 - acc: 0.7810
Epoch 35/100
105/105 [==============================] - 0s 38us/sample - loss: 0.5705 - acc: 0.8952
Epoch 36/100
105/105 [==============================] - 0s 28us/sample - loss: 0.5897 - acc: 0.8286
Epoch 37/100
105/105 [==============================] - 0s 32us/sample - loss: 0.5507 - acc: 0.8476
Epoch 38/100
105/105 [==============================] - 0s 40us/sample - loss: 0.5455 - acc: 0.8571
Epoch 39/100
105/105 [==============================] - 0s 35us/sample - loss: 0.5461 - acc: 0.7714
Epoch 40/100
105/105 [==============================] - 0s 30us/sample - loss: 0.5338 - acc: 0.8857
Epoch 41/100
105/105 [==============================] - 0s 30us/sample - loss: 0.5320 - acc: 0.8857
Epoch 42/100
105/105 [==============================] - 0s 39us/sample - loss: 0.5619 - acc: 0.8095
Epoch 43/100
105/105 [==============================] - 0s 34us/sample - loss: 0.5163 - acc: 0.9048
Epoch 44/100
105/105 [==============================] - 0s 27us/sample - loss: 0.5207 - acc: 0.8190
Epoch 45/100
105/105 [==============================] - 0s 58us/sample - loss: 0.5057 - acc: 0.9238
Epoch 46/100
105/105 [==============================] - 0s 36us/sample - loss: 0.5325 - acc: 0.8190
Epoch 47/100
105/105 [==============================] - 0s 48us/sample - loss: 0.4963 - acc: 0.9048
Epoch 48/100
105/105 [==============================] - 0s 37us/sample - loss: 0.4920 - acc: 0.9143
Epoch 49/100
105/105 [==============================] - 0s 32us/sample - loss: 0.4881 - acc: 0.9333
Epoch 50/100
105/105 [==============================] - 0s 39us/sample - loss: 0.5124 - acc: 0.7619
Epoch 51/100
105/105 [==============================] - 0s 31us/sample - loss: 0.4961 - acc: 0.8000
Epoch 52/100
105/105 [==============================] - 0s 28us/sample - loss: 0.4917 - acc: 0.8571
Epoch 53/100
105/105 [==============================] - 0s 41us/sample - loss: 0.4725 - acc: 0.9238
Epoch 54/100
105/105 [==============================] - 0s 30us/sample - loss: 0.4882 - acc: 0.7905
Epoch 55/100
105/105 [==============================] - 0s 33us/sample - loss: 0.5038 - acc: 0.8000
Epoch 56/100
105/105 [==============================] - 0s 30us/sample - loss: 0.4682 - acc: 0.8476
Epoch 57/100
105/105 [==============================] - 0s 30us/sample - loss: 0.4647 - acc: 0.9048
Epoch 58/100
105/105 [==============================] - 0s 47us/sample - loss: 0.4608 - acc: 0.9048
Epoch 59/100
105/105 [==============================] - 0s 34us/sample - loss: 0.4672 - acc: 0.8190
Epoch 60/100
105/105 [==============================] - 0s 32us/sample - loss: 0.4595 - acc: 0.8286
Epoch 61/100
105/105 [==============================] - 0s 31us/sample - loss: 0.4653 - acc: 0.8571
Epoch 62/100
105/105 [==============================] - 0s 28us/sample - loss: 0.4489 - acc: 0.9333
Epoch 63/100
105/105 [==============================] - 0s 31us/sample - loss: 0.4434 - acc: 0.8762
Epoch 64/100
105/105 [==============================] - 0s 38us/sample - loss: 0.4442 - acc: 0.9238
Epoch 65/100
105/105 [==============================] - 0s 34us/sample - loss: 0.4446 - acc: 0.8571
Epoch 66/100
105/105 [==============================] - 0s 31us/sample - loss: 0.4589 - acc: 0.8286
Epoch 67/100
105/105 [==============================] - 0s 33us/sample - loss: 0.4350 - acc: 0.9143
Epoch 68/100
105/105 [==============================] - 0s 33us/sample - loss: 0.4391 - acc: 0.7905
Epoch 69/100
105/105 [==============================] - 0s 34us/sample - loss: 0.4373 - acc: 0.9429
Epoch 70/100
105/105 [==============================] - 0s 35us/sample - loss: 0.4464 - acc: 0.8571
Epoch 71/100
105/105 [==============================] - 0s 49us/sample - loss: 0.4245 - acc: 0.9238
Epoch 72/100
105/105 [==============================] - 0s 41us/sample - loss: 0.4204 - acc: 0.9333
Epoch 73/100
105/105 [==============================] - 0s 49us/sample - loss: 0.4173 - acc: 0.9048
Epoch 74/100
105/105 [==============================] - 0s 41us/sample - loss: 0.4202 - acc: 0.9143
Epoch 75/100
105/105 [==============================] - 0s 47us/sample - loss: 0.4487 - acc: 0.8000
Epoch 76/100
105/105 [==============================] - 0s 37us/sample - loss: 0.4085 - acc: 0.9429
Epoch 77/100
105/105 [==============================] - 0s 35us/sample - loss: 0.4146 - acc: 0.8952
Epoch 78/100
105/105 [==============================] - 0s 34us/sample - loss: 0.4130 - acc: 0.9143
Epoch 79/100
105/105 [==============================] - 0s 38us/sample - loss: 0.4185 - acc: 0.9048
Epoch 80/100
105/105 [==============================] - 0s 36us/sample - loss: 0.4006 - acc: 0.9524
Epoch 81/100
105/105 [==============================] - 0s 32us/sample - loss: 0.4437 - acc: 0.7810
Epoch 82/100
105/105 [==============================] - 0s 34us/sample - loss: 0.3941 - acc: 0.9429
Epoch 83/100

105/105 [==============================] - 0s 41us/sample - loss: 0.3970 - acc: 0.9429
Epoch 84/100
105/105 [==============================] - 0s 34us/sample - loss: 0.3934 - acc: 0.9524
Epoch 85/100
105/105 [==============================] - 0s 35us/sample - loss: 0.3912 - acc: 0.9429
Epoch 86/100
105/105 [==============================] - 0s 34us/sample - loss: 0.3949 - acc: 0.8857
Epoch 87/100
105/105 [==============================] - 0s 36us/sample - loss: 0.3873 - acc: 0.9429
Epoch 88/100
105/105 [==============================] - 0s 30us/sample - loss: 0.3815 - acc: 0.9524
Epoch 89/100
105/105 [==============================] - 0s 32us/sample - loss: 0.3817 - acc: 0.9524
Epoch 90/100
105/105 [==============================] - 0s 33us/sample - loss: 0.3799 - acc: 0.9333
Epoch 91/100
105/105 [==============================] - 0s 38us/sample - loss: 0.3756 - acc: 0.9619
Epoch 92/100
105/105 [==============================] - 0s 31us/sample - loss: 0.3810 - acc: 0.9524
Epoch 93/100
105/105 [==============================] - 0s 31us/sample - loss: 0.3834 - acc: 0.9429
Epoch 94/100
105/105 [==============================] - 0s 34us/sample - loss: 0.4110 - acc: 0.8667
Epoch 95/100
105/105 [==============================] - 0s 32us/sample - loss: 0.3700 - acc: 0.9619
Epoch 96/100
105/105 [==============================] - 0s 31us/sample - loss: 0.3838 - acc: 0.8762
Epoch 97/100
105/105 [==============================] - 0s 37us/sample - loss: 0.3828 - acc: 0.9238
Epoch 98/100
105/105 [==============================] - 0s 32us/sample - loss: 0.3615 - acc: 0.9238
Epoch 99/100
105/105 [==============================] - 0s 34us/sample - loss: 0.3662 - acc: 0.8952
Epoch 100/100
105/105 [==============================] - 0s 35us/sample - loss: 0.3727 - acc: 0.8952

### Model Prediction

In [237]:
model.evaluate(test_x, test_y)

45/45 [==============================] - 0s 499us/sample - loss: 0.2886 - acc: 0.9556

[0.2886086285114288, 0.95555556]

### Save the Model

In [231]:
model.save("iris_model.h5")

In [232]:
!ls

11_Iris.csv
Boston_Housing_Prices_tensorflow.py
Iris.csv
iris_model.h5
prices.csv
R6_Internal_Lab_UpdatedTF2_Prices_Iris.ipynb

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?

In [238]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(10, activation=tf.nn.relu, input_shape=(4,)),  # input shape required
  tf.keras.layers.Dense(10, activation=tf.nn.relu),
  tf.keras.layers.Dense(3, activation=tf.nn.softmax)
])

In [239]:
model.compile(tf.keras.optimizers.SGD(), loss='categorical_crossentropy', metrics=['accuracy'])

In [240]:
model.fit(train_x, train_y, epochs=100)

Epoch 1/100
105/105 [==============================] - 0s 597us/sample - loss: 2.0296 - acc: 0.3524
Epoch 2/100
105/105 [==============================] - 0s 30us/sample - loss: 1.4515 - acc: 0.3524
Epoch 3/100
105/105 [==============================] - 0s 31us/sample - loss: 1.2820 - acc: 0.3524
Epoch 4/100
105/105 [==============================] - 0s 32us/sample - loss: 1.2035 - acc: 0.3524
Epoch 5/100
105/105 [==============================] - 0s 38us/sample - loss: 1.1514 - acc: 0.3524
Epoch 6/100
105/105 [==============================] - 0s 32us/sample - loss: 1.1278 - acc: 0.3524
Epoch 7/100
105/105 [==============================] - 0s 40us/sample - loss: 1.1018 - acc: 0.3524
Epoch 8/100
105/105 [==============================] - 0s 36us/sample - loss: 1.0851 - acc: 0.3524
Epoch 9/100
105/105 [==============================] - 0s 33us/sample - loss: 1.0755 - acc: 0.3524
Epoch 10/100
105/105 [==============================] - 0s 31us/sample - loss: 1.0655 - acc: 0.3524
Epoch 11/100
105/105 [==============================] - 0s 42us/sample - loss: 1.0554 - acc: 0.3524
Epoch 12/100
105/105 [==============================] - 0s 35us/sample - loss: 1.0404 - acc: 0.3524
Epoch 13/100
105/105 [==============================] - 0s 31us/sample - loss: 1.0203 - acc: 0.3524
Epoch 14/100
105/105 [==============================] - 0s 56us/sample - loss: 0.9981 - acc: 0.3619
Epoch 15/100
105/105 [==============================] - 0s 34us/sample - loss: 0.9789 - acc: 0.3619
Epoch 16/100
105/105 [==============================] - 0s 36us/sample - loss: 0.9600 - acc: 0.3619
Epoch 17/100
105/105 [==============================] - 0s 36us/sample - loss: 0.9475 - acc: 0.3619
Epoch 18/100
105/105 [==============================] - 0s 34us/sample - loss: 0.9420 - acc: 0.3619
Epoch 19/100
105/105 [==============================] - 0s 35us/sample - loss: 0.9359 - acc: 0.3524
Epoch 20/100
105/105 [==============================] - 0s 32us/sample - loss: 0.9316 - acc: 0.3524
Epoch 21/100
105/105 [==============================] - 0s 35us/sample - loss: 0.9243 - acc: 0.3714
Epoch 22/100
105/105 [==============================] - 0s 34us/sample - loss: 0.9178 - acc: 0.5143
Epoch 23/100
105/105 [==============================] - 0s 33us/sample - loss: 0.9118 - acc: 0.5810
Epoch 24/100
105/105 [==============================] - 0s 40us/sample - loss: 0.9064 - acc: 0.6190
Epoch 25/100
105/105 [==============================] - 0s 36us/sample - loss: 0.9004 - acc: 0.6381
Epoch 26/100
105/105 [==============================] - 0s 29us/sample - loss: 0.8951 - acc: 0.6095
Epoch 27/100
105/105 [==============================] - 0s 34us/sample - loss: 0.8889 - acc: 0.6286
Epoch 28/100
105/105 [==============================] - 0s 35us/sample - loss: 0.8836 - acc: 0.6095
Epoch 29/100
105/105 [==============================] - 0s 35us/sample - loss: 0.8780 - acc: 0.6286
Epoch 30/100
105/105 [==============================] - 0s 31us/sample - loss: 0.8720 - acc: 0.6190
Epoch 31/100
105/105 [==============================] - 0s 40us/sample - loss: 0.8662 - acc: 0.6095
Epoch 32/100
105/105 [==============================] - 0s 36us/sample - loss: 0.8594 - acc: 0.6190
Epoch 33/100
105/105 [==============================] - 0s 32us/sample - loss: 0.8530 - acc: 0.6190
Epoch 34/100
105/105 [==============================] - 0s 33us/sample - loss: 0.8475 - acc: 0.6190
Epoch 35/100
105/105 [==============================] - 0s 34us/sample - loss: 0.8414 - acc: 0.6190
Epoch 36/100
105/105 [==============================] - 0s 38us/sample - loss: 0.8349 - acc: 0.6286
Epoch 37/100
105/105 [==============================] - 0s 30us/sample - loss: 0.8298 - acc: 0.6286
Epoch 38/100
105/105 [==============================] - 0s 38us/sample - loss: 0.8237 - acc: 0.6190
Epoch 39/100
105/105 [==============================] - 0s 42us/sample - loss: 0.8183 - acc: 0.6286
Epoch 40/100
105/105 [==============================] - 0s 36us/sample - loss: 0.8119 - acc: 0.6286
Epoch 41/100
105/105 [==============================] - 0s 40us/sample - loss: 0.8060 - acc: 0.6286
Epoch 42/100
105/105 [==============================] - 0s 33us/sample - loss: 0.7999 - acc: 0.6286
Epoch 43/100
105/105 [==============================] - 0s 45us/sample - loss: 0.7946 - acc: 0.6286
Epoch 44/100
105/105 [==============================] - 0s 34us/sample - loss: 0.7892 - acc: 0.6286
Epoch 45/100
105/105 [==============================] - 0s 48us/sample - loss: 0.7841 - acc: 0.6286
Epoch 46/100
105/105 [==============================] - 0s 35us/sample - loss: 0.7791 - acc: 0.6286
Epoch 47/100
105/105 [==============================] - 0s 32us/sample - loss: 0.7735 - acc: 0.6286
Epoch 48/100
105/105 [==============================] - 0s 36us/sample - loss: 0.7689 - acc: 0.6286
Epoch 49/100
105/105 [==============================] - 0s 45us/sample - loss: 0.7636 - acc: 0.6286
Epoch 50/100
105/105 [==============================] - 0s 35us/sample - loss: 0.7582 - acc: 0.6286
Epoch 51/100
105/105 [==============================] - 0s 34us/sample - loss: 0.7533 - acc: 0.6286
Epoch 52/100
105/105 [==============================] - 0s 29us/sample - loss: 0.7483 - acc: 0.6286
Epoch 53/100
105/105 [==============================] - 0s 35us/sample - loss: 0.7446 - acc: 0.6286
Epoch 54/100
105/105 [==============================] - 0s 40us/sample - loss: 0.7405 - acc: 0.6286
Epoch 55/100
105/105 [==============================] - 0s 31us/sample - loss: 0.7339 - acc: 0.6286
Epoch 56/100
105/105 [==============================] - 0s 33us/sample - loss: 0.7302 - acc: 0.6286
Epoch 57/100
105/105 [==============================] - 0s 33us/sample - loss: 0.7249 - acc: 0.6286
Epoch 58/100
105/105 [==============================] - 0s 30us/sample - loss: 0.7204 - acc: 0.6286
Epoch 59/100
105/105 [==============================] - 0s 39us/sample - loss: 0.7163 - acc: 0.6286
Epoch 60/100
105/105 [==============================] - 0s 40us/sample - loss: 0.7109 - acc: 0.6286
Epoch 61/100
105/105 [==============================] - 0s 39us/sample - loss: 0.7069 - acc: 0.6286
Epoch 62/100
105/105 [==============================] - 0s 36us/sample - loss: 0.7022 - acc: 0.6286
Epoch 63/100
105/105 [==============================] - 0s 31us/sample - loss: 0.6986 - acc: 0.6286
Epoch 64/100
105/105 [==============================] - 0s 49us/sample - loss: 0.6931 - acc: 0.6286
Epoch 65/100
105/105 [==============================] - 0s 41us/sample - loss: 0.6894 - acc: 0.6286
Epoch 66/100
105/105 [==============================] - 0s 31us/sample - loss: 0.6840 - acc: 0.6286
Epoch 67/100
105/105 [==============================] - 0s 36us/sample - loss: 0.6806 - acc: 0.6286
Epoch 68/100
105/105 [==============================] - 0s 37us/sample - loss: 0.6759 - acc: 0.6286
Epoch 69/100
105/105 [==============================] - 0s 29us/sample - loss: 0.6714 - acc: 0.6286
Epoch 70/100
105/105 [==============================] - 0s 39us/sample - loss: 0.6684 - acc: 0.6286
Epoch 71/100
105/105 [==============================] - 0s 32us/sample - loss: 0.6630 - acc: 0.6286
Epoch 72/100
105/105 [==============================] - 0s 34us/sample - loss: 0.6586 - acc: 0.6381
Epoch 73/100
105/105 [==============================] - 0s 31us/sample - loss: 0.6533 - acc: 0.6286
Epoch 74/100
105/105 [==============================] - 0s 39us/sample - loss: 0.6486 - acc: 0.6286
Epoch 75/100
105/105 [==============================] - 0s 35us/sample - loss: 0.6444 - acc: 0.6286
Epoch 76/100
105/105 [==============================] - 0s 42us/sample - loss: 0.6404 - acc: 0.6286
Epoch 77/100
105/105 [==============================] - 0s 41us/sample - loss: 0.6377 - acc: 0.6286
Epoch 78/100
105/105 [==============================] - 0s 34us/sample - loss: 0.6343 - acc: 0.6286
Epoch 79/100
105/105 [==============================] - 0s 33us/sample - loss: 0.6289 - acc: 0.6286
Epoch 80/100
105/105 [==============================] - 0s 33us/sample - loss: 0.6251 - acc: 0.6286
Epoch 81/100
105/105 [==============================] - 0s 34us/sample - loss: 0.6220 - acc: 0.6286
Epoch 82/100
105/105 [==============================] - 0s 35us/sample - loss: 0.6184 - acc: 0.6286
Epoch 83/100

105/105 [==============================] - 0s 36us/sample - loss: 0.6138 - acc: 0.6286
Epoch 84/100
105/105 [==============================] - 0s 30us/sample - loss: 0.6116 - acc: 0.6286
Epoch 85/100
105/105 [==============================] - 0s 31us/sample - loss: 0.6069 - acc: 0.6286
Epoch 86/100
105/105 [==============================] - 0s 37us/sample - loss: 0.6036 - acc: 0.6286
Epoch 87/100
105/105 [==============================] - 0s 33us/sample - loss: 0.6008 - acc: 0.6286
Epoch 88/100
105/105 [==============================] - 0s 36us/sample - loss: 0.5977 - acc: 0.6286
Epoch 89/100
105/105 [==============================] - 0s 35us/sample - loss: 0.5934 - acc: 0.6286
Epoch 90/100
105/105 [==============================] - 0s 35us/sample - loss: 0.5908 - acc: 0.6286
Epoch 91/100
105/105 [==============================] - 0s 40us/sample - loss: 0.5871 - acc: 0.6286
Epoch 92/100
105/105 [==============================] - 0s 28us/sample - loss: 0.5839 - acc: 0.6286
Epoch 93/100
105/105 [==============================] - 0s 33us/sample - loss: 0.5806 - acc: 0.6286
Epoch 94/100
105/105 [==============================] - 0s 34us/sample - loss: 0.5775 - acc: 0.6286
Epoch 95/100
105/105 [==============================] - 0s 37us/sample - loss: 0.5751 - acc: 0.6286
Epoch 96/100
105/105 [==============================] - 0s 31us/sample - loss: 0.5722 - acc: 0.6286
Epoch 97/100
105/105 [==============================] - 0s 34us/sample - loss: 0.5695 - acc: 0.6381
Epoch 98/100
105/105 [==============================] - 0s 37us/sample - loss: 0.5674 - acc: 0.6476
Epoch 99/100
105/105 [==============================] - 0s 36us/sample - loss: 0.5640 - acc: 0.6286
Epoch 100/100
105/105 [==============================] - 0s 29us/sample - loss: 0.5618 - acc: 0.6286

In [241]:
model.evaluate(test_x, test_y)

45/45 [==============================] - 0s 587us/sample - loss: 0.4628 - acc: 0.7556

[0.4628284421232012, 0.75555557]